appVersion=4.1.0
springBootVersion=4.1.0
springBootDMVersion=1.1.7
mapstructVersion=1.6.3
lombokMapstructVersion=0.2.0
springdocVersion=3.0.3
# Gradle config
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.read-only=true
org.gradle.configuration-cache.problems=warn