server:
  error:
    include-message: always
spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        ddl-auto: create-drop
        hbm2dll:
          create_namespaces: true

  datasource:
    url: jdbc:h2:mem:testdb

