server:
  error:
    include-message: always
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC

  datasource:
    url: jdbc:h2:mem:testdb

